# Generated by Django 6.0.4 on 2026-05-06 12:04

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Admin'), ('user', 'User')], default='user', max_length=20)),
                ('unit_ids', models.JSONField(blank=True, default=list, help_text='List of unit IDs this user has access to')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='app1_user_set', related_query_name='app1_user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='app1_user_set', related_query_name='app1_user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='HourlyAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_id', models.PositiveIntegerField(db_index=True)),
                ('hour', models.DateTimeField(db_index=True)),
                ('avg_active_power_kw', models.FloatField(default=0)),
                ('min_active_power_kw', models.FloatField(default=0)),
                ('max_active_power_kw', models.FloatField(default=0)),
                ('total_energy_kwh', models.FloatField(default=0)),
                ('reading_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-hour'],
                'unique_together': {('unit_id', 'hour')},
            },
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_id', models.PositiveIntegerField(db_index=True)),
                ('timestamp', models.FloatField(help_text='Unix timestamp')),
                ('block1_start_reg', models.PositiveIntegerField(default=40100)),
                ('block1_raw', models.JSONField(help_text='Raw registers from block 1')),
                ('block2_start_reg', models.PositiveIntegerField(default=40138)),
                ('block2_raw', models.JSONField(help_text='Raw registers from block 2')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('voltage', models.FloatField(blank=True, null=True)),
                ('current', models.FloatField(blank=True, null=True)),
                ('active_power_kw', models.FloatField(blank=True, null=True)),
                ('reactive_power_kvar', models.FloatField(blank=True, null=True)),
                ('apparent_power_kva', models.FloatField(blank=True, null=True)),
                ('energy_today_kwh', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['unit_id', 'timestamp'], name='app1_sensor_unit_id_3d6612_idx'), models.Index(fields=['-timestamp'], name='app1_sensor_timesta_fb1d6a_idx')],
            },
        ),
    ]
