# Generated by Django 6.0.4 on 2026-04-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_id', models.PositiveIntegerField(db_index=True)),
                ('timestamp', models.FloatField()),
                ('block1_start_reg', models.PositiveIntegerField()),
                ('block1_raw', models.JSONField()),
                ('block2_start_reg', models.PositiveIntegerField()),
                ('block2_raw', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['unit_id', 'timestamp'], name='app1_sensor_unit_id_3d6612_idx')],
            },
        ),
    ]
