# Generated by Django 6.0.4 on 2026-04-27 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensorreading',
            options={'ordering': ['-updated_at']},
        ),
        migrations.RemoveIndex(
            model_name='sensorreading',
            name='app1_sensor_unit_id_3d6612_idx',
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='unit_id',
            field=models.PositiveIntegerField(db_index=True, unique=True),
        ),
    ]
