# Generated by Django 6.0.4 on 2026-05-01 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_sensorreading_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_id', models.PositiveIntegerField(db_index=True)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('voltage_v', models.FloatField()),
                ('current_a', models.FloatField()),
                ('kw_total', models.FloatField()),
                ('kvar_total', models.FloatField()),
                ('kva_total', models.FloatField()),
                ('kwh_del', models.FloatField()),
                ('pf_total', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['unit_id', 'timestamp'], name='app1_energy_unit_id_68cdd6_idx')],
            },
        ),
    ]
