# Generated by Django 6.0.4 on 2026-05-01 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_energyhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_id', models.PositiveIntegerField(db_index=True)),
                ('timestamp', models.FloatField(db_index=True)),
                ('datetime', models.DateTimeField(db_index=True)),
                ('block1_start_reg', models.PositiveIntegerField()),
                ('block1_raw', models.JSONField()),
                ('block2_start_reg', models.PositiveIntegerField()),
                ('block2_raw', models.JSONField()),
                ('voltage', models.FloatField(blank=True, null=True)),
                ('current', models.FloatField(blank=True, null=True)),
                ('kw_total', models.FloatField(blank=True, null=True)),
                ('kvar_total', models.FloatField(blank=True, null=True)),
                ('kva_total', models.FloatField(blank=True, null=True)),
                ('kwh_delivered', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.RemoveIndex(
            model_name='energyhistory',
            name='app1_energy_unit_id_68cdd6_idx',
        ),
        migrations.DeleteModel(
            name='EnergyHistory',
        ),
        migrations.DeleteModel(
            name='SensorReading',
        ),
        migrations.AddIndex(
            model_name='energyreading',
            index=models.Index(fields=['unit_id', 'timestamp'], name='app1_energy_unit_id_d16bfa_idx'),
        ),
        migrations.AddIndex(
            model_name='energyreading',
            index=models.Index(fields=['datetime'], name='app1_energy_datetim_9af6aa_idx'),
        ),
    ]
