# Generated by Django 6.0.4 on 2026-05-01 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_sensorreading_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensorreading',
            name='created_at',
        ),
        migrations.CreateModel(
            name='SensorReadingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_id', models.PositiveIntegerField(db_index=True)),
                ('timestamp', models.FloatField()),
                ('block1_raw', models.JSONField()),
                ('block2_raw', models.JSONField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['unit_id', 'recorded_at'], name='app1_sensor_unit_id_a06917_idx')],
            },
        ),
    ]
