# Generated by Django 6.0.4 on 2026-05-01 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_remove_sensorreading_created_at_sensorreadinghistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='HourlyAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_id', models.PositiveIntegerField(db_index=True)),
                ('hour', models.DateTimeField(db_index=True)),
                ('avg_kw', models.FloatField()),
                ('avg_kva', models.FloatField()),
                ('count', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['hour'],
            },
        ),
        migrations.CreateModel(
            name='SensorHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_id', models.PositiveIntegerField(db_index=True)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('voltage_v', models.FloatField()),
                ('current_a', models.FloatField()),
                ('active_kw', models.FloatField()),
                ('reactive_kvar', models.FloatField()),
                ('apparent_kva', models.FloatField()),
                ('power_factor', models.FloatField()),
                ('energy_kwh', models.FloatField()),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SensorLatest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('timestamp', models.DateTimeField()),
                ('voltage_v', models.FloatField()),
                ('current_a', models.FloatField()),
                ('active_kw', models.FloatField()),
                ('reactive_kvar', models.FloatField()),
                ('apparent_kva', models.FloatField()),
                ('power_factor', models.FloatField()),
                ('energy_kwh', models.FloatField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'sensor latest',
            },
        ),
        migrations.DeleteModel(
            name='SensorReading',
        ),
        migrations.RemoveIndex(
            model_name='sensorreadinghistory',
            name='app1_sensor_unit_id_a06917_idx',
        ),
        migrations.DeleteModel(
            name='SensorReadingHistory',
        ),
        migrations.AlterUniqueTogether(
            name='hourlyaggregate',
            unique_together={('unit_id', 'hour')},
        ),
        migrations.AddIndex(
            model_name='sensorhistory',
            index=models.Index(fields=['unit_id', 'timestamp'], name='app1_sensor_unit_id_a92594_idx'),
        ),
    ]
