# Generated by Django 6.0.4 on 2026-05-01 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_hourlyaggregate_sensorhistory_sensorlatest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('timestamp', models.FloatField()),
                ('block1_start_reg', models.PositiveIntegerField()),
                ('block1_raw', models.JSONField()),
                ('block2_start_reg', models.PositiveIntegerField()),
                ('block2_raw', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.DeleteModel(
            name='HourlyAggregate',
        ),
        migrations.RemoveIndex(
            model_name='sensorhistory',
            name='app1_sensor_unit_id_a92594_idx',
        ),
        migrations.DeleteModel(
            name='SensorHistory',
        ),
        migrations.DeleteModel(
            name='SensorLatest',
        ),
    ]
