# Generated by Django 6.0.4 on 2026-05-01 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_sensorreading_delete_hourlyaggregate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HourlyAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_id', models.PositiveIntegerField(db_index=True)),
                ('hour', models.DateTimeField(db_index=True)),
                ('avg_active_power_kw', models.FloatField(default=0)),
                ('min_active_power_kw', models.FloatField(default=0)),
                ('max_active_power_kw', models.FloatField(default=0)),
                ('total_energy_kwh', models.FloatField(default=0)),
                ('reading_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-hour'],
            },
        ),
        migrations.AlterModelOptions(
            name='sensorreading',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveField(
            model_name='sensorreading',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='active_power_kw',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='apparent_power_kva',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='current',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='energy_today_kwh',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='reactive_power_kvar',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='voltage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='block1_raw',
            field=models.JSONField(help_text='Raw registers from block 1'),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='block1_start_reg',
            field=models.PositiveIntegerField(default=40100),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='block2_raw',
            field=models.JSONField(help_text='Raw registers from block 2'),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='block2_start_reg',
            field=models.PositiveIntegerField(default=40138),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='timestamp',
            field=models.FloatField(help_text='Unix timestamp'),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='unit_id',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='sensorreading',
            index=models.Index(fields=['unit_id', 'timestamp'], name='app1_sensor_unit_id_3d6612_idx'),
        ),
        migrations.AddIndex(
            model_name='sensorreading',
            index=models.Index(fields=['-timestamp'], name='app1_sensor_timesta_fb1d6a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='hourlyaggregate',
            unique_together={('unit_id', 'hour')},
        ),
    ]
